### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by spyn0x** [krlplm/sitereview#1]
Hi there, 
I'm new in Python, so just tried to use this script, bud didn't work...

`Traceback (most recent call last):
  File "sitereview.py", line 66, in <module>
    site(args.url)
  File "sitereview.py", line 42, in site
    response = s.sitereview(url)
  File "sitereview.py", line 25, in sitereview
    return json.loads(self.req.content)
  File "C:\Users\Spyn0x\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Spyn0x\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Spyn0x\AppData\Local\Programs\Python\Python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

Any suggestion?

**Comment by mathieuchateau** [comment]
@spyn0x : url site used by script is dead, 404 when going with a browser

**Comment by krlplm** [comment]
script is updated now!
